<?php

namespace App\Pipeline\Writers;

use App\Pipeline\Contracts\WriterContract;
use App\Pipeline\Data\ArticleDraft;
use App\Pipeline\Data\WriteRequest;
use Illuminate\Support\Str;

/**
 * Plumbing-test driver: produces a deterministic article from the
 * transcript without calling any model. Set WRITER_DRIVER=fake.
 */
class FakeWriter implements WriterContract
{
    public function write(WriteRequest $request): ArticleDraft
    {
        $firstSentence = Str::of($request->transcript)->before('.')->limit(80);

        $body = "## From the garden\n\n"
            .trim($request->transcript)
            ."\n\n## Notes\n\n_Generated by the fake writer driver — swap WRITER_DRIVER to ollama or anthropic for real articles._";

        return new ArticleDraft(
            title: (string) ($firstSentence->isEmpty() ? 'Notes from the garden' : $firstSentence),
            bodyMarkdown: $body,
        );
    }

    public function summarizeStyle(array $samples): string
    {
        return 'Fake voice profile based on '.count($samples).' sample(s).';
    }

    public function identifier(): string
    {
        return 'fake:writer';
    }
}
